import 'package:dart_ncnn_yolov8/dart_ncnn_yolov8.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'ncnn_yolo_options.freezed.dart';

@freezed
class NcnnYoloOptions with _$NcnnYoloOptions {
  const factory NcnnYoloOptions({
    @Default(true) bool autoDispose,
    @Default(yoloProbThresholdDefault) double probThreshold,
    @Default(yoloNmsThresholdDefault) double nmsThreshold,
    @Default(yoloTargetSizeDefault) int targetSize,
    @Default(yoloNumClassDefault) int numClass,
    @Default(yoloUseGPUDefault) bool useGPU,
  }) = _NcnnYoloOptions;
}

final ncnnYoloOptions = StateProvider(
  (ref) => const NcnnYoloOptions(
    numClass: 80,
    useGPU: false,
  ),
  name: 'ncnnYoloOptions',
);

final labels = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush'
];
